server:
  port: 8080

spring:
  profiles:
    active: local

  h2.console:
    enabled: true
  #datasource.url: jdbc:h2:./db/testDb
  jpa:
    show_sql: true
    hibernate.ddl-auto: create

  main:
    web-environment: true

  data:
    mongodb:
      port: 27017

shrt:
  service-url: http://localhost:8080
