server:
  port: 8080

spring:
  profiles:
    active: local

  datasource.url: jdbc:h2:./db/testDb
  jpa.hibernate.ddl-auto: create

  main:
    web-environment: true

  data:
    mongodb:
      port: 27017
